import { createSlice, PayloadAction } from "@reduxjs/toolkit";

export interface User {
  _id: string;
  username: string;
  role: string;
  deposit: number;
}

// Define the shape of the AuthState
export interface AuthState {
  user: User | null;
  token: string | null;
  deposit: number;
}

// Initial state for the AuthState
const initialState: AuthState = {
  user: null,
  token: null,
  deposit: 0,
};

// Create a Redux slice for authentication
const authSlice = createSlice({
  name: "auth", // Name of the slice
  initialState, // Initial state
  reducers: {
    // Define reducer functions for actions
    // Use the PayloadAction type to declare the contents of `action.payload`
    login: (state, action: PayloadAction<AuthState>) => {
      // Update the state with user and token from the action payload
      state.user = action.payload.user;
      state.deposit = action.payload.user?.deposit || 0;
      state.token = action.payload.token;
    },
    logout: (state) => {
      // Clear user and token from the state when logging out
      state.user = null;
      state.deposit = 0;
      state.token = null;
    },
    updateDeposit(state, action: PayloadAction<number>) {
      // Update the user's deposit amount in the state
      if (state.user) state.user.deposit = action.payload;
      state.deposit = action.payload;
    },
    resetDeposit(state) {
      // Reset the user's deposit amount in the state
      state.deposit = 0;
    },
  },
});

// Export the actions created by the slice
export const { resetDeposit, updateDeposit, login, logout } = authSlice.actions;

// Export the reducer function generated by the slice
export default authSlice.reducer;
